---
Name: app
After: silvershop/config#shopconfig
---

Page:
  extensions:
    - InsiteCommonEcommrcePageExtension

Page_Controller:
  extensions:
    - InsiteCommonEcommrcePageControllerExtension

i18n:
  default_locale: en_US

ShopCurrency:
  decimal_delimiter: '.'
  thousand_delimiter: ','

Product:
  global_allow_purchase: true
  # length_unit: 'M'
  # weight_unit: 'Pounds'
  db: # Revised decimal places
    CostPrice: 'Currency(19,2)'
    BasePrice: 'Currency(19,2)'
    Weight: 'Decimal(12,3)'
    Height: 'Decimal(12,3)'
    Width: 'Decimal(12,3)'
    Depth: 'Decimal(12,3)'

# Change the dimensions of product thumbnails
Product_Image:
  thumbnail_width: 140
  thumbnail_height: 100
  content_image_width: 200
  large_image_width: 200

ProductCategory:
  include_child_groups: true
  must_have_price: false
  sort_options:
    'Title' : 'Alphabetical'
    'Price' : 'Lowest Price'

#ShoppingCart_Controller:
  # Redirect to the cart page after manipulating the shopping cart
  #direct_to_cart_page: true
  # disable security token for cart-links
  #disable_security_token: true

CheckoutConfig:
  member_creation_enabled: true
  membership_required: true

Order:
  modifiers:
    - 'SimpleShippingModifier'
  cancel_before_payment: false
  cancel_before_processing: false
  cancel_before_sending: false
  cancel_before_sending: false
  cancel_after_sending: false
  # Change / add order status, added Refunded
  db:
    Status: Enum('Unpaid,Paid,Processing,Refunded,Sent,Complete,AdminCancelled,MemberCancelled,Cart','Cart')
  # For logging order status changes & emailing notifications to customers
  log_status:
    - Processing
    - Sent
    - MemberCancelled
    - AdminCancelled

OrderManipulation:
  allow_cancelling: true
  allow_paying: true


ProductCategory:
  extensions:
    - SimpleListingHolderExtension
